######
# This is example of config file for smtp-to-mattermost.
# There are two sections:
#   * default: this is default options for sending message to mattermost.
#   * rules: list of rules for matching email message. Currently 'from',
#            'to' and 'subject' fields are supported. Their values can be
#            regexp to match corresponding email field.
#
# Each rule in list tested in order. First matched rule is used to update
# values from 'default' section with its 'options' subsection.
######

default:
    channel: 'general'
    username: smtp-to-mattermost
    icon_url: ''
    mattermost_webhook: "https://mattermost.server.local/hooks/aaaaaaaaaaaaaaaaaaaaaaaaaa"
    debug: false
    format: "subject: %(subject)s; body: %(body)s"  ## default mattermost message format


rules:
    - name: Monit rule
      from: monit@.*

      options:
          username: monit
          channel: 'monitoring'
          icon_url: 'https://bitbucket.org/tildeslash/monit/avatar/128'
          debug: false


    - name: Cron rule
      from: root@localhost
      subject: Cron.*

      options:
          username: cron
          channel: 'cron'
          icon_url: ''
          debug: true  ## will output full email with all headers
